global using ERC.UserManagement.API;
global using ERC.UserManagement.API.Routers;
global using ERC.UserManagement.Application;
global using ERC.UserManagement.Application.Features.UserAccounts.Commands;
global using ERC.UserManagement.Infrastructure;
global using ERC.UserManagement.Infrastructure.Persistence.Database;
global using MediatR;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.OpenApi.Models;